<!DOCTYPE html>
<html lang="en"><!-- InstanceBegin template="/Templates/main.dwt.php" codeOutsideHTMLIsLocked="false" -->
<head>
<!-- InstanceBeginEditable name="doctitle" -->
<title>Ignet</title>
<!-- InstanceEndEditable -->
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="shortcut icon" href="/favicon.ico"/>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<script src="https://cdn.tailwindcss.com"></script>
<script>
  tailwind.config = {
    theme: {
      extend: {
        colors: {
          navy: '#1a365d',
          'navy-dark': '#102a4c',
          accent: '#ed8936',
          success: '#38a169',
          background: '#f7fafc',
          text: '#1a202c',
        },
        fontFamily: {
          sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        },
      }
    }
  }
</script>
<link href="css/bmain.css" rel="stylesheet" type="text/css" />
<!-- InstanceBeginEditable name="head" --><!-- InstanceEndEditable -->
</head>
<body class="bg-[#f7fafc] text-[#1a202c] font-sans" id="main_body">
<?php
include('inc/template_top.php');
?>
<main class="max-w-7xl mx-auto px-4 py-6">
  <!-- InstanceBeginEditable name=”Main” -->

  <h1 class=”text-2xl font-bold text-[#1a365d] mb-4”>Introduction</h1>

  <div class=”text-sm text-gray-700 leading-relaxed space-y-3 max-w-4xl”>

    <h2 class=”text-lg font-bold text-[#1a365d] mt-6 mb-2”>Overview</h2>
    <p>The Ignet (Integrated gene network) project is a centrality- and ontology-based literature discovery system for analyzing and visualizing biological gene interaction networks using all PubMed literature papers. Currently Ignet focuses on the literature mining of human gene interaction networks. The Ignet program is generated based on a literature mining strategy that we named “CONDL”, which represents the Centrality and Ontology-based Network Discovery using Literature data. Ignet is co-developed by three groups led by Dr. Yongqun “Oliver” He at the University of Michigan, USA, Dr. Junguk Hur at the University of North Dakota, USA, and Dr. Arzucan Özgür from Bogazici University. The details about CONDL and its case study application have been described in the papers: <a href=”http://www.ncbi.nlm.nih.gov/pubmed/21624163” class=”text-[#2b6cb0] hover:underline”>Ozgur et al., 2011</a>, <a href=”http://www.ncbi.nlm.nih.gov/pubmed/23256563” class=”text-[#2b6cb0] hover:underline”>Hur et al., 2012</a>, and more <a href=”(Yongqun He) AND ((Junguk Hur) OR (Arzucan Ozgur))” class=”text-[#2b6cb0] hover:underline”>here</a>.</p>

    <h2 class=”text-lg font-bold text-[#1a365d] mt-6 mb-2”>CONDL Strategy</h2>
    <p>Our CONDL strategy was initially applied to the literature mining of the Interferon-gamma (IFN-γ; Gene symbol: IFNG) and vaccine-mediated gene interaction networks. IFNG is vital in immune defense against bacterial and viral infections and tumor. It also regulates various immune responses that are often critical for induction of protective immunity generated by vaccines. Initially we used a centrality-based literature discovery approach to study IFN-γ and vaccine-mediated gene interaction network. Our study identified a generic IFNG network that contains 1,060 genes and 26,313 interactions among these genes (Reference: <a href=”http://www.ncbi.nlm.nih.gov/pubmed/20625487” class=”text-[#2b6cb0] hover:underline”>Ozgur et al., 2010</a>). As a subset of this generic IFN-γ network, the vaccine-specific subnetwork contains 102 genes and 154 interactions. However, this literature mining strategy misses the identification of those sentences that include specific vaccine names (e.g., BCG) without mentioning the words “vaccine”, “vaccination”, or their derivatives. Therefore, we used the VO hierarchy definitions to get more specific vaccine names and their relations, and used them for further literature mining. Our study found that more results were identified (Reference: <a href=”http://www.ncbi.nlm.nih.gov/pubmed/21624163” class=”text-[#2b6cb0] hover:underline”>Ozgur et al., 2011</a>). Then such a CONDL strategy was proposed. Later we used the same CONDL strategy to study the fever and vaccine specific human gene interaction networks (Reference: <a href=”http://www.ncbi.nlm.nih.gov/pubmed/23256563” class=”text-[#2b6cb0] hover:underline”>Hur et al., 2012</a>).</p>

    <!--p>In 1965 Wheelock <em>et al.</em> first reported  Interferon-gamma (IFN-γ)-like virus inhibitor induced in supernatant fluid of  cultures of fresh human leukocytes following incubation with phytohemagglutinin. In early 1970s, IFN-γ was further studied, and its name was eventually  designated. IFN-γ is the only type II IFN family member. It is secreted by  activated immune cells - primarily T and NK cells, but also B-cells, NKT cells  and professional antigen presenting cells. IFN-γ is vital in immune defense against  bacterial and viral infections and tumor. IFN-γ has been widely studied and  found critical in anti-infectious host defense, inflammatory conditions,  cancer, and auto-immune diseases. The most striking phenotype from mice lacking  either IFN-γ or its receptor is increased susceptibility to bacterial and viral  pathogens. IFN-γ is also critical for tumor  immuno-surveillance as assessed using spontaneous, transplantable and chemical  carcinogen-induced experimental tumors. Additionally, IFN-γ is found important  in leukocyte homing, cellular adhesion, immunoglobulin class switching, T  helper cell polarity, antigen presentation, cell cycle arrest and apoptosis,  neutrophil trafficking and NK cell activation. It also regulates various immune  responses that are often critical for induction of protective immunity  generated by vaccines.   </p-->

    <h2 class=”text-lg font-bold text-[#1a365d] mt-6 mb-2”>Centrality Analysis</h2>
    <p>Our CONDL approach integrates text mining with network centrality analysis to study various gene interaction networks. Our approach uses a natural language processing (NLP) and a machine learning based method to automatically extract gene interaction networks from the biomedical literature. To rank the genes in the literature-mined networks and to identify the most important ones we analyze the networks from centrality perspective. We calculate four different types of centralities (see reference: <a href=”https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2718658/” class=”text-[#2b6cb0] hover:underline”>PMC2718658</a>):</p>
    <ul class=”list-disc list-inside space-y-1 pl-2”>
      <li><em>Degree centrality</em> — the number of neighbors of a node</li>
      <li><em>Eigenvector centrality</em> — a function of the centralities of its neighbors</li>
      <li><em>Closeness centrality</em> — the inverse sum of the distances from the node to the other nodes in the network</li>
      <li><em>Betweenness centrality</em> — the proportion of the shortest paths between all pairs of nodes that pass through the node in interest. Different centralities measure different levels of importance. For example, in betweenness centrality a node is considered important if it occurs on many shortest paths between other nodes, whereas in degree centrality a node is considered important if it is connected to many other nodes.</li>
    </ul>

    <h2 class=”text-lg font-bold text-[#1a365d] mt-6 mb-2”>Ontology Integration</h2>
    <p>One novel feature in Ignet is that its development is accompanied with our development of the Interaction Network Ontology (INO). INO contains more than 800 interaction keywords organized in a hierarchical structure. These terms are aligned with the Basic Formal Ontology (<a href=”http://www.ifomis.org/bfo” class=”text-[#2b6cb0] hover:underline”>BFO</a>). An example of an INO term is “increase”, whose parent term in INO is “positive regulation”, which is a child term of “regulation” and “interaction”. In INO, 21 words are listed as synonyms for the term “increase” — for example, increased, increasing, elevated, and enhanced. These terms are all used for literature retrieval, enabling comprehensive coverage of all “increase” interaction types.</p>

    <h2 class=”text-lg font-bold text-[#1a365d] mt-6 mb-2”>Development History</h2>
    <p>The Ignet project was initiated in response to community requests for a web server to store analyzed data and provide a user-friendly interface for querying and visualizing gene interaction networks. We initially developed Ignet for analyses of IFNG gene networks, and later extended it to mine all possible human gene interactions based on the literature. The Ignet results are updated periodically. In each dynamic update, Ignet retrieves and stores PubMed abstract data, extracts gene-gene relationships, executes centrality analysis, and stores the results in the Ignet database for users to query.</p>

    <!-- p>The novelty of Ignet is two-fold. First, Ignet is the first  web-based literature mining system that is based on network centrality analysis. Second, Ignet uses the newly developed INO to explore the interaction types found in the extracted gene-gene interaction sentences. The ontology-based  approach makes it more powerful to recognize and cluster various interaction types.</p -->

  </div>

  <!-- InstanceEndEditable -->
</main>
<?php include('inc/template_footer.php'); ?>
</body>
<!-- InstanceEnd --></html>
