<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><!-- InstanceBegin template="/Templates/main.dwt.php" codeOutsideHTMLIsLocked="false" -->
<head>
<!-- InstanceBeginEditable name="doctitle" -->
<title>Ignet</title>
<!-- InstanceEndEditable -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<link rel="shortcut icon" href="/favicon.ico"/>
<link href="css/bmain.css" rel="stylesheet" type="text/css" />
<!-- InstanceBeginEditable name="head" --><!-- InstanceEndEditable -->
</head>
<body style="margin:0px; background-image:url(images/bg_2008-08-21.2.gif)" id="main_body">
<?php 

include('inc/template_top.php');
?>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td width="160" valign="top" style="min-width:160px">
<?php 
include('inc/template_left.php');
?>
		</td>
		<td valign="top">
		<div style="margin:6px 10px 16px 10px; border-top:2px #4A2F65 solid">
		<!-- InstanceBeginEditable name="Main" -->
  <h3 style="text-align:center"><strong>Introduction</strong></h3>
 <p>The Ignet (Integrated gene network) project is a centrality- and ontology-based liteature discovery system for analyzing and visualizing biological gene interaction networks using all PubMed literature papers. Currently Ignet focuses on the literature mining of human gene interaction networks. The Ignet program is generated based on a literature mining strategy that we named "CONDL", which represents the Centrality and Ontology-based Network Discovery using Literature data. Ignet is co-developed by three groups led by Dr. Yongqun "Oliver" He at the University of Michigan, USA, Dr. Junguk Hur at the University of North Dakoda, USA, and Dr. Arzucan Özgür from Bogazici University. The details about CONDL and its case study application have been described in the papers: <a href="http://www.ncbi.nlm.nih.gov/pubmed/21624163">Ozgur et al., 2011</a>, <a href="http://www.ncbi.nlm.nih.gov/pubmed/23256563">Hur et al, 2012</a>), and more <a href="(Yongqun He) AND ((Junguk Hur) OR (Arzucan Ozgur))">Here</a>.</p>
<p>Our CONDL strategy was initially applied to the literature mining of the Interferon-gamma (IFN-γ; Gene symbol: IFNG) and vaccine-mediated gene interaction networks. IFNG is vital in immune defense against bacterial and viral infections and tumor. It also regulates various immune responses that are often critical for induction of protective immunity generated by vaccines. Initially we used a centrality-based literature discovery approach to study IFN-γ and vaccine-mediated gene interaction network. Our study identified indicated a generic IFNG network that contains 1,060 genes and 26,313 interactions among these genes (Reference: <a href="http://www.ncbi.nlm.nih.gov/pubmed/20625487">Ozgur et al, 2010</a>). As a subset of this generic IFN-γ network, the vaccine-specific subnetwork contains 102 genes and 154 interactions. However, this literature mining strategy misses the identification of those sentences that include specifci vaccine names (e.g., BCG) without mentioning the words &quot;vaccine&quot;, &quot;vaccination&quot;, or their derivatives. Therefore, we used the VO hierarchy definitions to get more specific vaccine names and their relations, and used them for further literature mining. Our study found that more results were identified (Reference: <a href="http://www.ncbi.nlm.nih.gov/pubmed/21624163">Ozgur et al., 2011</a>). Then such a CONDL strategy was proposed. Later we used the same CONDL strategy to study the fever and vaccine specific human gene interaction networks (Reference: <a href="http://www.ncbi.nlm.nih.gov/pubmed/23256563">Hur et al, 2012</a>). </p>
			
 <!--p>In 1965 Wheelock <em>et al.</em> first reported  Interferon-gamma (IFN-γ)-like virus inhibitor induced in supernatant fluid of  cultures of fresh human leukocytes following incubation with phytohemagglutinin. In early 1970s, IFN-γ was further studied, and its name was eventually  designated. IFN-γ is the only type II IFN family member. It is secreted by  activated immune cells - primarily T and NK cells, but also B-cells, NKT cells  and professional antigen presenting cells. IFN-γ is vital in immune defense against  bacterial and viral infections and tumor. IFN-γ has been widely studied and  found critical in anti-infectious host defense, inflammatory conditions,  cancer, and auto-immune diseases. The most striking phenotype from mice lacking  either IFN-γ or its receptor is increased susceptibility to bacterial and viral  pathogens. IFN-γ is also critical for tumor  immuno-surveillance as assessed using spontaneous, transplantable and chemical  carcinogen-induced experimental tumors. Additionally, IFN-γ is found important  in leukocyte homing, cellular adhesion, immunoglobulin class switching, T  helper cell polarity, antigen presentation, cell cycle arrest and apoptosis,  neutrophil trafficking and NK cell activation. It also regulates various immune  responses that are often critical for induction of protective immunity  generated by vaccines.   </p-->
			
<p>Our CONDL approach integrats text mining with network centrality analysis to study various gene interaction networks. Our approach uses a natural language processing (NLP) and a machine learning based method to automatically extract gene interaction networks from the biomedical  literature. To rank the genes in the literature-mined networks and to identify the most important ones we analyze the networks from centrality perspective. We calculate four different types of centralities (see reference: <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2718658/">PMC2718658</a>): </p>
<ul>
  <li><em>degree centrality</em> (the  number of neighbors of a node), </li>
  <li><em>eigenvector centrality</em> (function of the  centralities of its neighbors), </li>
  <li><em>closeness centrality</em> (inverse sum of the  distances from the node to the other nodes in the network), and </li>
  <li><em>betweenness  centrality</em> (the proportion of the shortest paths between all the pairs of  nodes that pass through the node in interest). Different centralities measure  different levels of importance. For example, in betweenness centrality a node  is considered important if it occurs on many shortest paths between other  nodes, whereas in degree centrality a node is considered important if it is  connected to many other nodes.</li>
</ul>
			
<p>One novel feature in Ignet is that its development is accompanied with our development of the Interaction Network Ontology (INO). INO contains more than 800 interaction keywords organized in a hierarchical structure. These terms are organized in INO using a hierarchical structure and  aligned with the Basic Formal ontology (<a href="http://www.ifomis.org/bfo">BFO</a>). An example of INO term is “increase”, whose parent term in INO is “positive  regulation”, which is a child term of “regulation” and “interaction”. In INO, 21 words were listed as “synonym” for the term “increase”, for example, increased, increasing, elevated, and enhanced. These terms were all used for  literature retrieval. We have used such strategy to obtain all types of "increase" interaction types. </p>
			
<p>The Ignet developed was initiated from our addressing the request by the community for us to develop a web server to store the analyzed data and provide a user-friendly web interface to query and visualize the analyzed data. To address this request, we have developed Ignet, a user-friendly web interface for the analyses of IFNG gene networks, and later we extended this to mine all possible human gene interactions based on the literature. The Ignet results are updated periodically. In each dynamic update, Ignet will retrieve and store PubMed abstract data, extract the gene-gene relationships, execute the centrality analysis, and store the results in Ignet database for users’ query.</p>
			
<!-- p>The novelty of Ignet is two-fold. First, Ignet is the first  web-based literature mining system that is based on network centrality analysis. Second, Ignet uses the newly developed INO to explore the interaction types found in the extracted gene-gene interaction sentences. The ontology-based  approach makes it more powerful to recognize and cluster various interaction types.</p -->
<p>&nbsp;</p>
        <!-- InstanceEndEditable -->
		</div>
		</td>
	</tr>
</table>
</body>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-4869243-4");
pageTracker._trackPageview();
</script>
<!-- InstanceEnd --></html>
