#!/usr/bin/env python3
"""Build t_doid_hierarchy from the Human Disease Ontology (OBO).

Why this exists
---------------
t_hdo stores a real DOID identifier per annotation (hdo_id, 7,213 distinct over
19.5M rows) but the API queries that table nowhere. Disease terms are instead
read from t_biosummary.hdo_term -- a comma-joined varchar -- so diseases are
handled as text and cannot be rolled up.

The concrete symptom is api/routes/dignet.py:

    _HDO_GENERIC_TERMS = frozenset({"disease", "syndrome", "disorder"})

Those are ontology classes, not arbitrary stopwords: "disease" is DOID:4, the
ROOT of the Disease Ontology. Filtering the root by name is both ad hoc and
incomplete -- it misses DOID:162 "cancer" (1.3M rows), which is just as broad.
With a hierarchy the same job is done by depth, which generalises.

Sibling of scripts/build_ino_hierarchy.py; same contract (additive SQL on
stdout, never ALTERs or DROPs an existing table). The INO script parses OWL
because INO ships as OWL; DOID ships as OBO, which is simpler to parse
correctly, so the parsing differs while the output shape matches.

Note on id form: t_hdo stores the colon form ("DOID:4"), so this emits the
colon form too. Do not normalise to underscores -- the join would silently
match nothing.

Usage:
    python3 scripts/build_doid_hierarchy.py --obo doid.obo > doid_hierarchy.sql
    mysql --defaults-file=~/.my.cnf ignet < doid_hierarchy.sql
"""
from __future__ import annotations

import argparse
import sys

TABLE = "t_doid_hierarchy"


def parse_obo(path: str) -> dict[str, dict]:
    """Return {doid: {"name", "parents", "obsolete"}} from an OBO file.

    Only [Term] stanzas are read; [Typedef] and the header are ignored.
    """
    terms: dict[str, dict] = {}
    cur: dict | None = None
    in_term = False

    with open(path, encoding="utf-8") as fh:
        for raw in fh:
            line = raw.rstrip("\n")
            if line.startswith("["):
                # Commit the previous stanza before switching context.
                if in_term and cur and cur.get("id"):
                    terms[cur["id"]] = {
                        "name": cur.get("name"),
                        "parents": cur.get("parents", []),
                        "obsolete": cur.get("obsolete", False),
                    }
                in_term = line.strip() == "[Term]"
                cur = {"parents": []} if in_term else None
                continue
            if not in_term or cur is None or not line:
                continue

            key, _, value = line.partition(": ")
            value = value.strip()
            if key == "id":
                cur["id"] = value
            elif key == "name":
                cur["name"] = value
            elif key == "is_a":
                # "DOID:10124 ! corneal disease" -> "DOID:10124"
                cur["parents"].append(value.split("!")[0].strip())
            elif key == "is_obsolete" and value.lower() == "true":
                cur["obsolete"] = True

    if in_term and cur and cur.get("id"):
        terms[cur["id"]] = {
            "name": cur.get("name"),
            "parents": cur.get("parents", []),
            "obsolete": cur.get("obsolete", False),
        }
    return terms


def compute_level(doid: str, terms: dict[str, dict], _seen: frozenset[str] = frozenset()) -> int:
    """Depth from a root. Cycles and dangling parents terminate at current depth."""
    if doid in _seen:
        return 0
    parents = terms.get(doid, {}).get("parents") or []
    if not parents:
        return 0
    return 1 + max(compute_level(p, terms, _seen | {doid}) for p in parents)


def sql_escape(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--obo", required=True, help="path to doid.obo")
    args = ap.parse_args()

    terms = parse_obo(args.obo)
    if not terms:
        print("ERROR: no [Term] stanzas parsed", file=sys.stderr)
        return 1

    obsolete = sum(1 for t in terms.values() if t["obsolete"])
    roots = [d for d, t in terms.items() if not t["parents"] and not t["obsolete"]]

    print(f"-- {TABLE}: generated by scripts/build_doid_hierarchy.py")
    print(f"-- terms: {len(terms)} | obsolete: {obsolete} | roots: {len(roots)}")
    print(f"""
CREATE TABLE IF NOT EXISTS {TABLE} (
  doid           VARCHAR(32)  NOT NULL,
  label          VARCHAR(255) DEFAULT NULL,
  parent_doid    VARCHAR(32)  DEFAULT NULL,
  level          INT          NOT NULL DEFAULT 0,
  is_obsolete    TINYINT(1)   NOT NULL DEFAULT 0,
  PRIMARY KEY (doid),
  KEY idx_parent (parent_doid),
  KEY idx_level (level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
""")

    rows = []
    for doid in sorted(terms):
        info = terms[doid]
        parents = info["parents"]
        # Primary is_a for tree display; DOID is a DAG, so a term may have
        # several parents. Depth uses the deepest path (see compute_level).
        parent = parents[0] if parents else None
        rows.append(
            "({}, {}, {}, {}, {})".format(
                sql_escape(doid),
                sql_escape(info["name"]),
                sql_escape(parent),
                compute_level(doid, terms),
                1 if info["obsolete"] else 0,
            )
        )

    print(f"REPLACE INTO {TABLE} (doid, label, parent_doid, level, is_obsolete) VALUES")
    # Chunked so a single statement does not exceed max_allowed_packet.
    chunk = 2000
    for i in range(0, len(rows), chunk):
        block = rows[i:i + chunk]
        terminator = ";" if i + chunk >= len(rows) else ";"
        print(",\n".join(block) + terminator)
        if i + chunk < len(rows):
            print(f"REPLACE INTO {TABLE} (doid, label, parent_doid, level, is_obsolete) VALUES")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
